---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy-ingress
  namespace: argocd
spec:
  project: core-applications
  sources:
    - repoURL: "https://haproxy-ingress.github.io/charts"
      targetRevision: "0.14.8"
      chart: haproxy-ingress
      helm:
        releaseName: shire
        valueFiles:
          - $values/argocd/shire-cluster/core-applications/haproxy-ingress/values.yaml
    - repoURL: "https://github.com/gabrielmuras/home.git"
      ref: values      
      targetRevision: HEAD
  destination:
    name: local
    namespace: haproxy-ingress
  syncPolicy: 
    automated: {}