
controller:
  replicaCount: 1
  ingressClassResource:
    enabled: true

  service:
    type: LoadBalancer
    annotations: 
      metallb.universe.tf/address-pool: shire-pool
  
  config:
    ssl-redirect-port: "443"
