- name: Add argocd chart
  kubernetes.core.helm_repository:
    name: argo
    repo_url: "https://argoproj.github.io/argo-helm"

- name: Deploy argocd
  kubernetes.core.helm:
    name: argocd
    namespace: argocd
    chart_ref: argo/argo-cd
    chart_version: "{{ argocd_chart_version }}"
    values: "{{ lookup('template', 'values/argocd/values.yml') | from_yaml }}"

- name: Deploy core app of apps
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'argocd/app-of-apps.yml') | from_yaml }}"