- name: update packages
  become: yes
  apt:
    name: "*"
    state: latest

- name: install useful packages
  become: yes
  apt:
    name:
      - vim
      - lvm2
      - htop
      - net-tools
      - curl
      - sudo
      - logrotate

