- name: Add user
  user:
    name: "{{ username }}"
    state: present
    shell: /bin/bash
    groups: "sudo"
    create_home: yes
    append: yes

- name: Add key
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_key }}"
    exclusive: True


- name: Allow sudo
  community.general.sudoers:
    name: user-sudo
    state: present
    user: "{{ username }}"
    commands: ALL