---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-applications
  namespace: argocd
  labels:
    name: core-applications
spec:
  project: default
  source:
    repoURL: https://github.com/gabrielmuras/home.git
    targetRevision: HEAD
    path: argocd/applications
    directory:
      recurse: true
  destination:
    name: local
  syncPolicy:
    syncOptions:   
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true